### ISSUE TITLE
Blinds not working

### ISSUE THREAD

**Issue by artfulsplodger** [jvmahon/smartshades#10]
Hi all! Hoping someone can help - got my blinds showing up in Home, but can't get them to operate, nothing happens when I tap on them. This is my config (XXX's replaced with addresses from the NEO app). Get no errors in Homebridge when trying to control the blinds, but nothing happens. Any help much appreciated! Thanks!

{
    "platform": "NEOShades",
    "name": "NEOShades",
    "host": "XXX",
    "controllerID": "XXX",
    "shades": [
        {
            "name": "Kitchen Left",
            "code": "XXX"
        },
        {
            "name": "Kitchen Right",
            "code": "XXX"
        }
    ]
}

**Comment by jvmahon** [comment]
Please post your "full" config.json as a .zip file.

**Comment by jvmahon** [comment]
Either that wasn't the "Full" file or you are missing the bridge, description, and platform fields and you don't have the file set up correctly.

See sample file:  https://github.com/jvmahon/homebridge-smartshades/blob/master/Config.Sample/config.json

**Comment by artfulsplodger** [comment]
Ah my bad I'm a total noob at this... for the name, username, port, pin, and description, do I just copy what's in your sample file? Or I need to get those details from the Neo app somewhere? Thanks for your help!

**Comment by artfulsplodger** [comment]
[JSON v2.zip](https://github.com/jvmahon/homebridge-smartshades/files/8209089/JSON.v2.zip)

Here's my current config, I'm just not sure what to put for;

1. name
2. username
3. port
4. pin 
5. description

Think I'm all set on host, controller ID, and code for each blind, just getting them from the Neo app

**Comment by jvmahon** [comment]
look at the example that I sent in the link, above.

You can use the same values for #1-#5 as shown in the example.
(though you might want to change "name" to your own name like "My Home Shades").

If in doubt, follow the example  closely.

**Comment by jvmahon** [comment]
Other sources of info. on settting up homebridge:

See:

https://github.com/homebridge/homebridge/wiki

https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting

**Comment by artfulsplodger** [comment]
I feel like such a noob but I just can't get it working even following your example config very closely...getting this error
<img width="1071" alt="Screenshot 2022-03-08 at 20 35 44" src="https://user-images.githubusercontent.com/101208639/157320600-0b9f81c0-0ec2-46ca-a59d-fd0e56dca4c0.png">
;

**Comment by artfulsplodger** [comment]
Could it be something to do with me running Homebridge on a Raspberry Pi?

**Comment by jvmahon** [comment]
Send me your *exact* config.json file and I'll try to help. Do not cut/past into word. I need the unchanged complete file.

No, I use it on a RPi and it works fine.

**Comment by artfulsplodger** [comment]
Really appreciate it!
[config.zip](https://github.com/jvmahon/homebridge-smartshades/files/8209681/config.zip)

**Comment by jvmahon** [comment]
OK, I think I'm seeing the problem.

You sent a file named "config.rtf".  That designates a "rich text file."  
The file must have the *exact* name "config.json"

Also, there was an extra     "platform": "NEOShades" statement at the end of the file.

Try the attached.

[Fixed Config.zip](https://github.com/jvmahon/homebridge-smartshades/files/8209773/Fixed.Config.zip)

**Comment by artfulsplodger** [comment]
Thanks but still having the same issue unfortunately, here's a screen recording: https://www.dropbox.com/s/zehqmj6hkjvqetx/Screen%20Recording%202022-03-08%20at%2021.47.03.mov?dl=0

**Comment by jvmahon** [comment]
I think this is a config-ui-x issue. I'll try to fix it so that config-ui-x doesn't add that extra statement. Might be able to get to it tonight, but just in case, give me a day or two.

**Comment by artfulsplodger** [comment]
No worries, appreciate it

**Comment by jvmahon** [comment]
I've added support for config-ui-x.

1. Update the plugin.
2. Then click on its "Settings" to configure.
3. Fill in the information following the example in the interface, below
4. Let me know if it works.

![image](https://user-images.githubusercontent.com/15061942/157350221-78f89354-1826-4ef3-ac76-9648a7de4873.png)

![image](https://user-images.githubusercontent.com/15061942/157350305-7b64da1a-9fbd-45a0-be41-2f123d350a54.png)

**Comment by artfulsplodger** [comment]
Thanks! Updated the plugin and filled out the settings, now no more errors on the log and they're showing up in the Home app but they don't close/open or move at all when I tap them. Here's the log - you can see the commands sent without errors but the blinds just don't move 

![Screenshot 2022-03-09 at 09 29 21](https://user-images.githubusercontent.com/101208639/157413301-c0af25fa-a5ca-4091-8c2c-50307e7bb3cc.png)

**Comment by jvmahon** [comment]
In the config file you previously sent, you had the following as the controllerID:
 "j0qzRAEgXqWKXzuUhZ0-_Q",

This is not the proper Controller ID.
The ID should be a long string of hex characters (0-1 and A-F).

To get the controller ID . . .

From the NEO Smart Blinds app on your phone, select the menu, then select the "Smart Controllers" option.

You will then see your controller listed.  You are looking for the string that starts with "ID".  It should be 24 characters long.

Underneath that is the correct IP address for the NEO controller that you will use to configure the plugin.  This is different from the IP address of the computer running homebridge.

**Comment by artfulsplodger** [comment]
I think I put all the values in correctly? 

![41F228E2-33FE-492B-9222-44BADDBFD221](https://user-images.githubusercontent.com/101208639/157448536-e144075b-4eb0-4e87-aec3-11c26c3600a4.jpeg)

**Comment by jvmahon** [comment]
That is where you get the values and it looks like you did use the correct values as shown on that page, but that controllerID is weird. It should be just hex digits. I'm not sure what to make of it. 

Does your controller look like the "wooden" box shown here: https://neosmartblinds.com/smartcontroller-integrations/

That's the controller this plugin was designed to work with. If not, can you show me exactly which controller you have.  I think there is a newer NEO Smart Blinds controller that has a different look - if you  are using the newer controller, maybe it isn't compatible with the plugin.

**Comment by jvmahon** [comment]
Also check that you have the latest NEO Smart Blinds app installed and, if you do need an app update, does the controller ID still appear the same after you update?

**Comment by jvmahon** [comment]
Yep, that's not a NEO hub and this plugin was written for the NEO.

I tried to find a programming interface for that hub, but couldn't find one online, so I don't have any way of making this work.

**Comment by artfulsplodger** [comment]
Ahh bugger. Neo do make reference to this one on their site (the C-BR300): https://neosmartblinds.com/smartcontroller-help/#scCBR300

**Comment by artfulsplodger** [comment]
I'll get in touch with Neo and see what they say. Appreciate your help with this!

**Comment by artfulsplodger** [comment]
Hey again! I heard back from Neo, I think they’ve written to you as well. Here’s their email and attachments;

![D1841078-F201-4D77-A35F-E953971AD978](https://user-images.githubusercontent.com/101208639/157512583-7fb01cf1-896b-4150-aa48-8f43ec4b1c12.png)

[open_local_http_protocol_v1_3.pdf](https://github.com/jvmahon/homebridge-smartshades/files/8217395/open_local_http_protocol_v1_3.pdf)

[open_tcp_protocol_v1_4.pdf](https://github.com/jvmahon/homebridge-smartshades/files/8217399/open_tcp_protocol_v1_4.pdf)

**Comment by jvmahon** [comment]
Try the update. For each shade, you will now also need to select the motor type in the configuration.  The plugin and NEO controller previously was limited to Bofu motors - apparently, they now support others, so you have to select yours from the list. I've included all the motors that their tech support person says are supported. Let me know if you get it working!

![image](https://user-images.githubusercontent.com/15061942/157543769-c7d09d58-d442-415c-be2a-e36ab4db4d57.png)

**Comment by artfulsplodger** [comment]
It's bloody working!!!!! Very grateful to you kind internet sir

**Comment by artfulsplodger** [comment]
Hey again! One slightly annoying thing I was wondering if you might have some advice for... here's the scenario: 

I have 4 blinds in my kitchen (all set in the 'Kitchen' room in Home). When I ask Siri to open/close the blinds, clearly the request is sent to HB one by one, because the blinds start moving one after the other rather than all at the same time. Issue is, Siri thinks the other blinds (after the first one starts moving) aren't responding, presumably because they don't immediately respond, so says 'X blind didn't respond', even though it does eventually start moving. Also, it doesn't look too slick them all moving at different times. Any idea how I might fix this? Cheers!

**Comment by jvmahon** [comment]
> Any idea how I might fix this? Cheers!

Try the following  and let me know if it works . . .


Each of your blinds has both a blind code and a room code. When you organize the shades in your "NEO Smart Blinds" application, all shades that are in the same room will have the same room code and this code can also be used to control the shades. So, instead of entering the 4 separate blinds into the plugin as separate items, enter the "room" code. Now your 4 shades will appear as just a single shade but it will control all the shades in the room at the same time.

![image](https://user-images.githubusercontent.com/15061942/157673843-404bd593-741e-4e69-b81e-15e56f88cc97.png)

**Comment by artfulsplodger** [comment]
It works! Thank you!

**Comment by jvmahon** [comment]
Looks like all is fixed so I'm going to close this comment. Re-open if there are further issues.

**Comment by artfulsplodger** [comment]
Thank you

**Comment by boboxx** [comment]
try homebridge-config-ui-x v4.43.0, it  fixed my blind issue!! looks like it was a "routing" issue.
